version: "3.3"

services:

  api:
    container_name: api
    build: .
    volumes:
      - .:/var/www/rest-api
    ports:
      - "80:3000"
    links:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:9.6-alpine
    ports:
      - "5432"
